### ISSUE TITLE
Foxx

### ISSUE THREAD

**Issue by Kr1ss-XD** [lastship/Rework-plugin.video.lastship#54]
### Actual Behavior / Tatsächliches Verhalten :

Provider Foxx funktioniert nicht

#### Additional Information / Weitere Informationen :

Neuer Player / DDOS-Prot. _(Blazingfast)_

##### Hardware, Kodi Version, Lastship Version :
Alle

**Comment by nokodemus** [comment]
Thx for adding this issue @Kr1ss-XD 

Any help for resolving this would be very appreciated :)

**Comment by Philps** [comment]
i have fixed this. see forum
